const candidatesData =  [
    {
      Id: 'EN45612',
      name: 'Jane Cooper',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN7485',
      name: 'Carles Nilson',
      phone: '+1 8652903311',
      email:"rudrateja9009@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'in-active',
      inPlacement: 'no',      
    },
    {
      Id: 'EN3215',
      name: 'Robert Fox',
      phone: '+1 8652903311',
      email:"aishwaryaaddala589@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN3625',
      name: 'Alice Danchik',
      phone: '+1 8652903311',
      email:"gouravkumar@yopmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN32415',
      name: 'Guy Hawkins',
      phone: '+1 8652903311',
      email:"jaxonlea848@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'in-active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN32561',
      name: 'Jane Cooper',
      phone: '+1 8652903311',
      email:"aishwaryaaddala589@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'no',      
    },
    {
      Id: 'EN4125',
      name: 'Cody Fishers',
      phone: '+1 8652903311',
      email:"rudrateja9009@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'in-active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN3245',
      name: 'Robert Fox',
      phone: '+1 8652903311',
      email:"aishwaryaaddala589@gmail.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'no',      
    },
    {
      Id: 'EN65422',
      name: 'Nick Logan',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN6523',
      name: 'Carles Nilson',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN5463',
      name: 'Nick Logan',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'in-active',
      inPlacement: 'no',      
    },
    {
      Id: 'EN45412',
      name: 'Carles Nilson',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    {
      Id: 'EN45124',
      name: 'Harris Bold',
      phone: '+1 8652903311',
      email:"aravind_21@outlook.com",
      createdBy:"Jane Cooper",
      createdOn:"07-Aug-2024",
      benchStatus: 'active',
      inPlacement: 'yes',      
    },
    
    ]

    module.exports = candidatesData;